dependencies:
  - curl=7.52.1
  - xz=5.2.2
  - r-irkernel
  - r-ggplot2=2.2.1
  - r-data.table=1.10.4
  - pip: 
     - mysqltsv==0.0.7
     - docopt==0.6.2
     - mwtypes==0.2.0
     - pywikibase==0.0.4
     - mwapi==0.5.1
     - mwreverts==0.1.5
     - pandas==0.20.1
     - matplotlib==2.0.2
     - seaborn==0.7.1
